### ISSUE TITLE
Third Party JSX support.

### ISSUE THREAD

**Issue by kunjee17** [fable-compiler/Feliz.JSX#2]
Hi, there are many third party libraries for react and solidjs. Until now we need to write wrapper around it. And it is still the way to go for most libraries. 

But is is possible to include third party jsx code? If yes how to do import for same?

**Comment by MangelMaxime** [comment]
It seems like you can't yet import the type from F# because of deduplicate feature of F# https://github.com/fable-compiler/Fable/issues/2912.

However, I support that when Fable see JSX code it just doesn't touch the code and so you can write valid JSX in it.

Looking at this issue https://github.com/fable-compiler/Fable/issues/3237 we can see someone using `import` directly from the JSX code because it valid JSX/JS code.

```fs
JSX.jsx
            $"""
        import {{ Input, Button }} from "react-chat-elements"
        <Input
            placeholder="Type here to send a message."
            defaultValue=""
            referance={inputRef}
            ....
```

**Comment by kunjee17** [comment]
@MangelMaxime Thanks I ll check that and close the issue afterwords. thanks a lot for reply

**Comment by kunjee17** [comment]
Import failing at compilation part. Not working sadly. :( . Still working on work around

**Comment by kunjee17** [comment]
I ll close this issue as I was able to write small wrapper and moved most of the code in tsx file.
